apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-desktop
  namespace: ueran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-desktop
  template:
    metadata:
      labels:
        app: ubuntu-desktop
    spec:
      containers:
      - name: desktop
        image: dorowu/ubuntu-desktop-lxde-vnc
        ports:
        - containerPort: 5900   # VNC
        - containerPort: 6080   # noVNC web access
        env:
        - name: RESOLUTION
          value: "1920x1080"
        - name: USER
          value: "ubuntu"
        - name: PASSWORD
          value: "ubuntu"
        - name: ALL_PROXY
          value: "socks5://ue-service.ueran.svc.cluster.local:1080"
        - name: http_proxy
          value: "socks5://ue-service.ueran.svc.cluster.local:1080"
        - name: https_proxy
          value: "socks5://ue-service.ueran.svc.cluster.local:1080"
        - name: NO_PROXY
          value: "localhost,127.0.0.1"
        # Start tsocks / proxychains for applications
        command:
        - bash
        - -c
        - |
          apt-get update && apt-get install -y tsocks proxychains curl
          # Configure tsocks
          echo -e "server = ue-service.ueran.svc.cluster.local\nserver_port = 1080\ndns = 1" > /etc/tsocks.conf
          # Configure proxychains
          echo -e "strict_chain\n[ProxyList]\nsocks5  ue-service.ueran.svc.cluster.local 1080" > /etc/proxychains.conf
          # Start LXDE VNC server
          /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-desktop
  namespace: ueran
spec:
  selector:
    app: ubuntu-desktop
  type: NodePort
  ports:
  - name: novnc
    port: 6080
    targetPort: 6080
    nodePort: 30680
    protocol: TCP
  - name: vnc
    port: 5900
    targetPort: 5900
    nodePort: 30590
    protocol: TCP
